version: '3.8'
name: academy
services:
  quotes:
    image: quotes
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - default
  hero:
    image: hero
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - default

networks:
  default:
    external:
      name: myNetwork